version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    docker:
      - image: 'circleci/golang:1.16'
    steps:
      - checkout
      - run:
          name: download helm
          command: >-
            wget
            https://gethelm.blob.core.windows.net/gethelm/helm-canary-windows-amd64.zip
            -O helm.zip
      - run:
          name: unzip
          command: unzip \helm.zip
      - persist_to_workspace:
          root: .
          paths:
            - windows-amd64/*
  generate-windows-installer:
    executor: win/default
    steps:
      - checkout
      - attach_workspace: null
        at: 'C:\tmp\workspace'
      - run: null
        name: Copy from Workspace
        command: 'Copy-Item "C:\tmp\workspace" . -Recurse'
      - run: null
        name: install innosetup and build
        command: .\build.ps1
      - store_artifacts: null
        path: output/
workflows:
  windows-installer-workflow:
    jobs:
      - build
      - generate-windows-installer:
          requires:
            - build
