version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    docker:
      - image: 'circleci/golang:1.16'
    steps:
      - checkout
      - run:
          name: create directory
          command: mkdir _dist
      - run:
          name: download helm
          command: >-
            wget
            https://gethelm.blob.core.windows.net/gethelm/helm-canary-windows-amd64.zip
            -O _dist/helm.zip
      - run:
          name: unzip
          command: cd _dist && unzip helm.zip
      - persist_to_workspace:
          root: .
          paths:
            - _dist/windows-amd64/*
  generate-windows-installer:
    executor: win/default
    steps:
      - checkout
      - attach_workspace:
          at: 'C:\tmp\workspace'
      - run:
          name: Copy from Workspace
          command: 'Copy-Item "C:\tmp\workspace\_dist\*" . -Recurse'
      - run:
          name: install innosetup and build
          command: .\build.ps1
      - store_artifacts:
          path: output/
workflows:
  windows-installer-workflow:
    jobs:
      - build
      - generate-windows-installer:
          requires:
            - build
