version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run:
          name: download helm #replace it with artifacts from build stage
          command: wget https://gethelm.blob.core.windows.net/gethelm/helm-canary-windows-amd64.zip -O helm.zip

      - run:
          name: unzip #can be ignored if we use artifcats
          command: unzip \helm.zip

      - persist_to_workspace:
          root: /tmp/build
          paths: 
            - windows-amd64/*

  generate-windows-installer:
    executor: win/default # executor type
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
         name: Copy from Workspace
         command: Copy-Item "/tmp/workspace" . -Recurse

      - run:
          name: install innosetup and build
          command: .\build.ps1

      - store_artifacts:
          path: output/

workflows:
  windows-installer-workflow:
    jobs:
      - build
      - generate-windows-installer:
          requires:
            - build
